# Generated by Django 6.0 on 2025-12-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
